### ISSUE TITLE
Why is PPO not coupled with OFE or OFE-dense

### ISSUE THREAD

**Issue by marcuswang6** [LQNew/Deeper_Larger_Actor-Critic_RL#1]
Is it not implemented yet or sth? Thx~

**Comment by LQNew** [comment]
Actually, I have not implemented PPO coupled with OFE or OFENet. Since I notice that in previous paper of OFE, PPO is considered as the baseline algorithm, but in the current paper of OFENet, PPO is discarded. Due to the limitation of computing resources and research considerations, I didn't implement PPO-ofenet or PPO-ofenet-dense when I opened source this project. However, in my codebase, these algorithms are easy to reproduce, I appriciate if you implement these algorithms and compare their performance. Also, I find the code link of PPO-ofenet provided by the author: https://www.merl.com/research/license/OFENet.

**Comment by LQNew** [comment]
> Is it not implemented yet or sth? Thx~

Actually, I have not implemented PPO coupled with OFE or OFENet. Since I notice that in previous paper of OFE, PPO is considered as the baseline algorithm, but in the current paper of OFENet, PPO is discarded. Due to the limitation of computing resources and research considerations, I didn't implement PPO-ofenet or PPO-ofenet-dense when I opened source this project. However, in my codebase, these algorithms are easy to reproduce, I appriciate if you implement these algorithms and compare their performance. Also, I find the code link of PPO-ofenet provided by the author: https://www.merl.com/research/license/OFENet.

**Comment by marcuswang6** [comment]
Thanks for your reply ~
